# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.1
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- export COCOAPODS_TRUNK_TOKEN=$COCOAPODS_TOKEN
# - pod install --project-directory=Example
script:
- set -e
- xcodebuild -workspace Example/NamingConventions.xcworkspace -scheme NamingConventions
#- pod trunk push --allow-warnings
deploy:
  provider: releases
  script: echo "POD TRUNK HERE"
  skip-cleanup: true
  api_key: $GITHUB_TOKEN 
  keep-history: true
  on:
    branch: master
tags: true
