#!/bin/bash
result=$(pod trunk me | grep "acidmanic.moayedi@gmail.com")

if [ -z "$result" ]
then 
	echo "Not registered to cocoapods. going to register."
	pod trunk register "acidmanic.moayedi@gmail.com" Acidmanic --description="Travis-Container"
else
	echo "Already registered"
fi

